In [1]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
from IPython.display import Image

In [3]:
img = cv2.imread("Piano_Sheet_Music.png", cv2.IMREAD_GRAYSCALE)

[[221 221 220 ... 224 224 224]
 [213 213 212 ... 217 217 217]
 [212 211 211 ... 216 216 216]
 ...
 [161 161 161 ... 133 134 134]
 [212 212 212 ... 200 200 200]
 [255 255 255 ... 255 255 255]]


In [ ]:
img_50 = cv2.threshold(img, 50, 255, cv2.THRESH_BINARY)
img_130 = cv2.threshold(img, 130, 255, cv2.THRESH_BINARY)
img_adp = cv2.adaptiveThreshold(img, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 11, 7)
